spring:
  datasource:
    url: jdbc:mysql://49.234.230.73:3306/bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Cj888888@
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
